### ISSUE TITLE
Handle clang

### ISSUE THREAD

**Issue by nagisa** [alexcrichton/cc-rs#119]
`clang` is a common C compiler. Some people (cough… me) prefer `clang` over `gcc` for mostly personal reasons and have `export CC=clang CXX=clang++` system/user/session wide.

Now, one of the major points that isn’t handled is cross compilation. For example when targetting `x86_64-pc-windows-gnu` from linux, `gcc-rs` crate “figures” out that it should try `x86_64-w64-mingw32-gcc`, but only if `CC` is not set. Otherwise it will use `CC` verbatim.

What could be done instead is `gcc-rs` could handle `clang` by simply comparing the compiler it is using with a string `"clang"`/`"clang++"`.

Figuring out the cross-compilation is not hard with clang either. You only need to add the `--target=$TARGET` flag.

**Comment by alexcrichton** [comment]
This sounds like a good idea to me, would you be interested in sending a PR?

**Comment by RReverser** [comment]
Maybe better to check first line of `--version` output from compiler? By default `cc` on MacOS is in fact clang, even though the name doesn't match, and also clang can be installed in a custom location / symlinked on other systems, so just checking name is not very reliable.

**Comment by vext01** [comment]
On a semi-related note, it would be nice to have an easy way to turn on `scan-build` and address sanitiser functionality easily.

**Comment by alexcrichton** [comment]
This is largely implemented nowadays, so I'm going to close this.
