### ISSUE TITLE
Support building Fortran libraries

### ISSUE THREAD

**Issue by Luthaf** [alexcrichton/cc-rs#138]
Would it be possible for this crate to support building Fortran code too?

It would allow to use existing Fortran code from Rust, even if this code is not available from the system: for example using a custom BLAS/Lapack on Windows, or some research code that might be hard to get otherwise.

I think that the current approach in this crate will work with Fortran compilers too: there are 3-4 majors compilers that uses different flags, and it should be possible to pattern-match on them to create the command line invocation.

It can also make sense to have a separated crate for this, but it would be largely copy-pasted from this one.

What do you think? I might try to contribute this if/when I find some time.

**Comment by alexcrichton** [comment]
Seems reasonable to me!

**Comment by alexcrichton** [comment]
I'm going to close this for now since I don't think it's something we necessarily want to actively add and I won't be pursuing myself, but PRs are of course always welcome!

**Comment by smoothdeveloper** [comment]
I'm starting something, for now, it is mostly a bare copy of this repository, and doesn't do much, but intend to make it work over time.

https://github.com/smoothdeveloper/fortranc-rs

Thanks for cc-rs 🙂.

**Comment by MattBolitho** [comment]
Just wanted to check in on this.

@smoothdeveloper - nice work on `fortranc-rs`! :) Did you get any further than the initial crate you published? I noticed the "This is not ready for usage yet, use for hacking only." disclaimer in the README.

To the maintainers (I guess @NobodyXu, @alexcrichton) is there still interest in supporting Fortran in the `cc` crate? Some of the original comments on this issue are a little old now, so thought it might be worth double-checking.

**Comment by smoothdeveloper** [comment]
@MattBolitho no further progress on my end, but it seemed to go ok in terms of extending and re-appropriating the code, even as both fortran and rust newbie. If there is interaction on the repository, it can definitely be pushed further.

**Comment by NobodyXu** [comment]
I will accept a PR given that it's in a maintainable shape, hopefully not introducing too much hard coded value
