### ISSUE TITLE
Are environment variables supposed to be printed out multiple times to stdout?

### ISSUE THREAD

**Issue by shepmaster** [alexcrichton/cc-rs#145]
[This bit seems odd](https://github.com/alexcrichton/gcc-rs/blob/36f19205be25c3a70fa8a1d93592a3e5ebbfa5f4/src/lib.rs#L1011-L1015):

```rust
    fn getenv(&self, v: &str) -> Option<String> {
        let r = env::var(v).ok();
        self.print(&format!("{} = {:?}", v, r));
        r
    }
```

Is it really supposed to be printing out each environment variable? My error output has all this at the beginning; note all the duplication:

```
--- stdout
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
TARGET = Some("x86_64-pc-windows-msvc")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
```

I do actually think that printing out the variables used / set is useful, but this feels like leftover debug prints. If so, I'd be happy to submit a PR removing them.

**Comment by alexcrichton** [comment]
Yeah I think it's fine to silence it if we've already printed it

**Comment by alexcrichton** [comment]
I think this has since been fixed, so closing.
