### ISSUE TITLE
add support for pkg_config

### ISSUE THREAD

**Issue by fneddy** [alexcrichton/cc-rs#147]
i often use [pkg_config](https://github.com/alexcrichton/pkg-config-rs) to find local library paths.

currently i am using my own function to add the found libraries to `gcc::Config`. is it possible to add something like this method to `gcc::Config`?

The Function:
``` rust
trait AddPkg {
    fn add_pkg_config(&mut self, pkg: pkg_config::Library);
}
impl AddPkg for gcc::Config {
    fn add_pkg_config(&mut self, pkg: pkg_config::Library) {
        for p in pkg.include_paths.into_iter() {
            self.include(p);
        }
        for p in pkg.link_paths.into_iter() {
            self.flag(&format!("-L{:?}", p));
        }
        for p in pkg.libs.into_iter() {
            self.flag(&format!("-l{}", p));
        }
        for p in pkg.framework_paths.into_iter() {
            self.flag(&format!("-F{:?}", p));
        }
        for p in pkg.frameworks.into_iter() {
            self.flag(&format!("-framework {}", p));
        }
    }
}
```

this allows to do this in the build.rs:

``` rust
let mut conf = gcc::Config::new();

...
// adding stuff here

let libaa = pkg_config::probe_library("aa").unwrap();
let libdb = pkg_config::probe_library("db").unwrap();

conf.add_pkg_config(libaa);
conf.add_pkg_config(libdb);

conf.compile();
```

full diff see [here](https://github.com/fneddy/gcc-rs/commit/a09af209b113931a6fde01058b4ffd28dfd38f37)

**Comment by alexcrichton** [comment]
This seems like a reasonable idea, but I'd probably prefer to delegate it to a separate crate for now rather than adding a dependency on pkg-config

**Comment by alexcrichton** [comment]
I'm going to close this for now as I think it should be relegated to an external crate.
