### ISSUE TITLE
Flags in mixed C/C++ compilation

### ISSUE THREAD

**Issue by julienschmidt** [alexcrichton/cc-rs#156]
I have a setup where a mix of C (.c) and C++ (.cc) files have to be compiled into one static linked library.  For the C files the `-std=c99` flag is necessary:
```rust
let mut library = gcc::Config::new();
library.include("library/src/include").flag("-std=c99");

for src in &library_src {
    libraryl.file(src);
}

library.compile("liblibrary.a");
```
However, the compilation fails on the first C++ file, since clang complains about the invalid flag:
```
cargo:warning=error: invalid argument '-std=c99' not allowed with 'C++/ObjC++'
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1
```

Other build tools solve this by allowing to define separate flags for C and C++ files (e.g. `flag_c` and `flag_cc`, while `flag` is used for all).

Is a setup like this already possible or can support be added?

**Comment by alexcrichton** [comment]
Ah yeah for now you'll have to build two separate `.a` files as gcc-rs isn't good at picking up which goes to which file. Does that work for you?

**Comment by julienschmidt** [comment]
That should probably work. Allowing to set different flags for different compilers would however be a convenient feature.

The problem in my case right now is that the include path seems to be ignored or headers files from the system are used instead for the so far single C++ file, so I can't report back with an definitive answer.

**Comment by alexcrichton** [comment]
Sounds bad! If that's the case it's definitely a bug! Let me know what you find though

**Comment by alexcrichton** [comment]
I'm going to close this for now since I think that using two builds is workable enough for now to solve this.
