### ISSUE TITLE
include doesn't support UNC paths on Windows

### ISSUE THREAD

**Issue by kornelski** [alexcrichton/cc-rs#169]
```rust
let cc = gcc::Config::new();
cc.include(std::fs::canonicalize("."));
```

Doesn't add absolute path of "." as the include dir (tested on Win10, MSVC). This is because Rust's `canonicalize()` makes a UNC path such as `\\?\C:\Foo`.

Stripping the `\\?\` prefix seems to solve the problem, but I don't know enough about UNC paths to know whether that's a good solution.

I use `fs::canonicalize()` as the easiest way to get absolute paths in build scripts of link/`-sys` dependencies to reliably pass the paths in env vars for other packages to consume, and it works well on Unix.

**Comment by alexcrichton** [comment]
Is this a bug with gcc-rs? Or is this a bug with cl.exe not accepting these paths? Do you have an error message?

**Comment by pornel** [comment]
cl.exe doesn't support UNC paths (`-IC:\foo` works as expected, `-I\\?\C:\foo` doesn't find includes)

So strictly speaking that's a bug in `cl.exe`, but I'm betting on `gcc-rs` to hide deficiencies of MSVC for me :)

**Comment by pornel** [comment]
I've released a crate that normalizes paths in a compatible way: https://gitlab.com/kornelski/dunce

It would be nice if that was built into the `include()` function here.

**Comment by alexcrichton** [comment]
I'm going to close this since it sounds like it was a bug in `cl.exe`, and I'd prefer to not add too much normalization to this crate.
