### ISSUE TITLE
Extract windows_registry module into its own crate

### ISSUE THREAD

**Issue by brson** [alexcrichton/cc-rs#174]
This crate is out of place here. Put it in another crate and make an internal dependency of this crate.

I'd suggest calling the crate `msvc` but we probably need to bikeshed the name further. @retep998 @alexcrichton preferences?

We'll also need to negotiate where it lives. At the least @alexcrichton will need to be a maintainer, so maybe he should just do this one.

**Comment by alexcrichton** [comment]
I'd probably go for a name like `msvc-finder` or something like that, I'm not sure this crate would be good enough to take a good name like `msvc`!

**Comment by retep998** [comment]
There's also bikeshedding on names in https://github.com/retep998/msvc-bunny/issues/1

**Comment by alexcrichton** [comment]
I'm going to close this as this isn't going to happen for the 1.0 release. When it does happen, though, I'll happily deprecate the functionality that already exists!
