### ISSUE TITLE
Rename crate

### ISSUE THREAD

**Issue by brson** [alexcrichton/cc-rs#186]
I think we want to rename this crate, but aren't quite sure what to name it to. I suggest "cc". @cmr will give us the name.

There's some concern though that "cc" is a unixism, and that actually this crate _could_ be expanded to be the simple way to do other types of native compilation in the future.

Still I suggest a contributor rename the crate to "cc" and bikeshed it on the PR.

**Comment by alexcrichton** [comment]
I personally like `cc` as it's nice, short, sweet, and  has tons of interpretations:

* C Compiler
* Compiler Crate
* Compiling C

...

**Comment by cmr** [comment]
I added @brson, @alexcrichton and @aturon as owners of the cc crate on crates.io

**Comment by dhardy** [comment]
Couldn't you pick a name that's a little less ambiguous, e.g. `cc-rs`? Not that I know much about the crate.

**Comment by cmr** [comment]
Why would you? Crate names shouldn't have "rust_" or "_rs" affixes. Note that this repo is named `gcc-rs` but the crate name is `gcc`...

**Comment by luser** [comment]
If you don't want to go all the way to `cc` then `c-compiler` seems like it would be a sensible name.

**Comment by opilar** [comment]
So the majority vote for `cc` name. Seems like this repo should be named as `cc-rs`. @alexcrichton, only you can do this?

**Comment by alexcrichton** [comment]
Indeed yeah! Once I get a little closer to publishing these changes I'll publish under the name `cc` and `gcc` and start deprecating the name `gcc`.
