### ISSUE TITLE
warnings should not be enabled by default

### ISSUE THREAD

**Issue by BusyJay** [alexcrichton/cc-rs#237]
Many project has their level of warnings control (and may contain -Werror but not contain -Wall), enable it by default may break their compilation. And because cmake-rs depends on gcc-rs, the change may also break projects that depends on cmake. More worse, cmake-rs doesn't have a way to make it off without add `-w` to cflags and cxxflags explicitly.

**Comment by alexcrichton** [comment]
The intention here is that `gcc` is primarily used for compiling local C code rather than upstream dependencies. I've just published a new version of the `cmake` crate which disables warnings (as it's intended to do) to retain the original behavior.

Are there more situations you were thinking of, though, where foreign code is compiled with warnings by accident?

**Comment by BusyJay** [comment]
Some projects uses makefile to maintain compilation dependencies. When wrapping those projects, usually either use shell or gather all the sources manually. In the latter case, the change will still break compilation. But this is a easy-to-fix case though because it depends on gcc-rs directly.

**Comment by alexcrichton** [comment]
Yeah I'd expect that any compilation of foreign sources to disable warnings, but I'd also expect the number of instances of that to be pretty small.

**Comment by BusyJay** [comment]
On windows, `/Wall` will introduce a lot of warnings, some are even from windows sdk itself. It seems like `/W4` is [recommended](https://msdn.microsoft.com/en-us/library/thxezb7y.aspx).

**Comment by alexcrichton** [comment]
Sure! I've pushed a commit to do that instead

**Comment by alexcrichton** [comment]
I'm going to close this and leave warnings enabled by default, but if there's any problems please be sure to let me know!
