### ISSUE TITLE
Support finding ndk-gcc from $ANDROID_NDK_HOME

### ISSUE THREAD

**Issue by mattico** [alexcrichton/cc-rs#247]
It would be nice if we could automatically find `arm-linux-androideabi-gcc` and the like based on the `$ANDROID_NDK_HOME`. This is probably not too hard to do. Perhaps there are other platforms that would benefit from something similar. Qt maybe?

**Comment by alexcrichton** [comment]
Oh interesting! Is this a standard env var on Android we can relatively rey on?

**Comment by mattico** [comment]
Not for running on Android, but for cross-compiling to android using the NDK. From my (somewhat limited) experience any android related tool will use this environment variable to find the NDK, so it's pretty much guaranteed to be set. It's easy enough to add gcc to your path, but it's also easy enough to support this env var. I opened this issue because someone on Reddit was surprised they needed to add android-gcc to their PATH, because no other android tool requires it.

**Comment by alexcrichton** [comment]
Is there perhaps some documentation online about where this env var is specified and what tools consume it?

(it's slightly worrying that the issue changed title to reference different env vars...)

**Comment by NickAtAccuPS** [comment]
A list of environment variables used by Android Studio can be found [here](https://developer.android.com/studio/command-line/variables.html). If the NDK has been installed via the Android SDK manager is can be found in ndk-bundle in the SDK root. They recommend using $ANDROID_SDK_ROOT but use the "depreciated" $ANDROID_HOME if it exists by default.

In Google's [Android ndk samples](https://github.com/googlesamples/android-ndk/wiki) they recommend $ANDROID_NDK_HOME for finding the NDK. It also looks like the variable is used by Android Studio if their [error messages](https://issuetracker.google.com/issues/37127636) are to be believed. I've seen several permutations of ANDROID, NDK, HOME, and ROOT used in the past, but this looks like the closest thing to an anointed environment variable for the NDK.

That said, it looks like like there might be an attempt to depreciate $ANDROID_NDK_HOME in favor of $ANDROID_NDK_ROOT (which would be consistent with the SDK). The only discussion I could find on the topic was in Swift's bugtracker [here](https://bugs.swift.org/browse/SR-1365):

> If anything, it should be ANDROID_NDK_ROOT, not ANDROID_NDK_HOME. Last time I pinned the Android folks down on these, they didn’t want to say any of these were official, but this is the explanation:
> 
> This was from David Turner from the Android team:
> [quote]
> 
> ANDROID_NDK_ROOT -> installation dir of NDK
> ANDROID_SDK_ROOT -> installation dir of SDK
> ANDROID_SDK_HOME -> location of SDK-related user files, defaults to
> ~/.android/ on Unix.
> 
> These variables are essentially used by the platform and SDK tools
> themselves, so are your best bet.
> 
> There is no ANDROID_NDK_HOME.
> 
> They are also used by the Chromium build for Android.
> [/quote]

**Comment by alexcrichton** [comment]
Awesome thanks for the links @NickAtAccuPS! Sounds like we should deinitely be using those to try to probe automatically for the various compilers.

**Comment by alexcrichton** [comment]
I'm going to close this for now since I suspect the layout of the android ndk has probably already changed since this was opened anyway. PRs to improve auto-detection of compiler names are always welcome, but otherwise I suspect this isn't too actionable over a year later!
