### ISSUE TITLE
sccache support? 

### ISSUE THREAD

**Issue by rrichardson** [alexcrichton/cc-rs#252]
Is this the appropriate crate in which to address potentially caching the results of compilation using scache?  

The Build::compile step just generates `cc` calls.  Perhaps we can have some sort of `prefix` configuration for Build which lets one specify a wrapper process such as sccache to the cc call. 

Thoughts?

**Comment by alexcrichton** [comment]
IIRC if you set `CC="sccache cc"` then it'll work, but you're right in that there's no way to configure ccache/sccache programmatically. Seems reasonable to add!

**Comment by rrichardson** [comment]
I think it will need a bit more finesse than setting env vars.   I ran into a couple issues when trying to compile ssh2.   I posted an issue in sccache :  https://github.com/mozilla/sccache/issues/189 

Will continue to dig.  There seem to be some best practices for getting CMake to use ccache, perhaps it will translate directly to sccache.

**Comment by alexcrichton** [comment]
Yes ccache + cmake tend to require some [intrusive configuration](https://github.com/rust-lang/rust/blob/305e02281bf6e7a5398f93f86c901316074be0a5/src/bootstrap/native.rs#L191-L230)...

**Comment by luser** [comment]
I don't think automatically adding caching to compile commands is a good idea, FWIW. If users want to use sccache in their build they should configure it themselves.

**Comment by rrichardson** [comment]
It wouldn't be on by default, it should be enabled by a switch of some sort.  

The challenge is actually internally changing some configurations when the `cache` switch is enabled.  If I knew exactly what those changes are, I'd have submitted them by now :/

**Comment by alexcrichton** [comment]
I think this is largely supported as well as we can today, so I'm going to close this.

**Comment by oli-cosmian** [comment]
If anyone else ends up here and just wants `sccache` to work without any system setup, place the following code snippet before your `Build::new()` invocation:

```rust
    if std::process::Command::new("sccache").arg("--version").status().is_ok() {
        std::env::set_var("CC", "sccache cc");
        std::env::set_var("CXX", "sccache c++");
    }
```
