### ISSUE TITLE
Gracefully handle super-long linker command lines

### ISSUE THREAD

**Issue by Flakebi** [alexcrichton/cc-rs#253]
This seems to the the same issue as rust-lang/rust#41190, just for this crate instead of rustc.
The linker fails if the command line is too long (32767 characters on windows).

Splitting a library into multiple libraries is currently a workaround.

**Comment by alexcrichton** [comment]
Seems plausible to me!

**Comment by alexcrichton** [comment]
I'm going to close this for now since I don't think it's really come up in practice all that much and splitting into multiple libraries should work for the rare cases it does come up.
