### ISSUE TITLE
Clarify use of `cpp_set_stdlib` flag

### ISSUE THREAD

**Issue by grovesNL** [alexcrichton/cc-rs#254]
Thanks for the great library.

In the [documentation for `cpp_set_stdlib`](https://github.com/alexcrichton/cc-rs/blob/master/src/lib.rs#L522) it states that the caller should ensure the flag is supported by the compiler. What is the recommended way of doing this? I was hoping the library could assist me here, because it already parses target from the environment.

I was interested in `try_get_compiler` and [using the returned `Tool`'s `ToolFamily`, but the `family` member is not public](https://github.com/alexcrichton/cc-rs/blob/master/src/lib.rs#L153). Is this intentional?

Alternatively, is there a way to accomplish this using `flag_if_supported`? Is there a reason why the semantics of `cpp_set_stdlib` couldn't allow for a similar `cpp_set_stdlib_if_supported` (just curious)?

**Comment by alexcrichton** [comment]
Hm I haven't personally used this flag much, but it typically comes up for linux/osx/msvc I believe, not for clang/gcc inside of linux

**Comment by grovesNL** [comment]
@alexcrichton Yes, this is for clang in OS X.

**Comment by alexcrichton** [comment]
Here I was thinking that gcc didn't exist any more on OSX...

**Comment by grovesNL** [comment]
I was trying to use gcc on OS X originally to get around this issue for now, but [it doesn't seem to work well with other libraries containing certain OS X types](https://travis-ci.org/gfx-rs/gfx/jobs/288817761#L1826). So I ended up using clang, which seems to be the happy path on OS X anyway, but [clang requires `cpp_set_stdlib` ](https://travis-ci.org/gfx-rs/gfx/jobs/288892138#L813).

**Comment by grovesNL** [comment]
This has been mostly resolved in #256, because we can decide whether or not to call `cpp_set_stdlib` based on the tool family. Although it could be interesting to follow the `*_if_supported` pattern and avoid the need to check entirely.

**Comment by alexcrichton** [comment]
Ok! I'll close this now that #256 is merged
