### ISSUE TITLE
build error with stable-gnu toolchain on Windows

### ISSUE THREAD

**Issue by gaoxiangxyz** [alexcrichton/cc-rs#258]
I meet below error when execute cargo build on Windows using toolchain stable-gnu.
It seems that I do not add right codes in build.rs, but how to handle these dependencies like 'rust-crypto v0.2.36'? Where is the c file for .file() and what for .compile()

Thanks.

Running "cargo build":
   Compiling parking_lot v0.4.8
   Compiling primal v0.2.3
   Compiling rocksdb-sys v0.3.0 (https://github.com/paritytech/rust-rocksdb#4364caec)
   Compiling rust-crypto v0.2.36
error: failed to run custom build command for `rust-crypto v0.2.36`
process didn't exit successfully: `e:\GitHub\parity\target\debug\build\rust-crypto-3042927cebbdfd04\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-Wall" "-Wextra" "-o" "e:\\GitHub\\parity\\target\\debug\\build\\rust-crypto-6ad0d314a4089618\\out\\src\\util_helpers.o" "-c" "src/util_helpers.c"
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-Wall" "-Wextra" "-o" "e:\\GitHub\\parity\\target\\debug\\build\\rust-crypto-6ad0d314a4089618\\out\\src\\aesni_helpers.o" "-c" "src/aesni_helpers.c"

--- stderr
thread 'main' panicked at '

Internal error occurred: Failed to find tool. Is `cc` installed? (see https://github.com/alexcrichton/gcc-rs#compile-time-requirements for help)

', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by alexcrichton** [comment]
Thanks for the report! I think though you may not have `cc` in PATH? Either that or something is configuring to use `"cc"` but it looks like it's not installed.
