### ISSUE TITLE
API breakable between version 0.3.51 and 0.3.52

### ISSUE THREAD

**Issue by antoyo** [alexcrichton/cc-rs#265]
Hello.
The API broke between version [0.3.51](https://docs.rs/gcc/0.3.51/gcc/) and [0.3.52](https://docs.rs/gcc/0.3.52/gcc/) as we can see from the documentation links (`gcc::Config` now being `gcc::Build` among other things).
Since we cannot use two different versions of the crate, this can cause issues when using dependencies that depend on different versions of the gcc crate.
Thanks to fix this issue.

**Comment by alexcrichton** [comment]
I believe that APIs were deprecated, but I don't think that anything was removed? Do you have a crate which builds with 0.3.51 and doesn't build with 0.3.52?

**Comment by antoyo** [comment]
Oh, I thought there was an API break because the doc does not show the deprecated types.
It would have been nice to keep them in the doc.
Sorry about that.
