### ISSUE TITLE
Add support for armv5te-unknown-linux-gnueabi

### ISSUE THREAD

**Issue by malbarbo** [alexcrichton/cc-rs#271]

**Comment by ljedrz** [comment]
@alexcrichton has the update containing this change landed? I'd like to resolve the [related FIXME](https://github.com/rust-lang/rust/blob/fc6b2c5fefa3e8793a5cab00a2d354d79137a306/src/ci/docker/dist-various-1/Dockerfile#L101). I'd also like to know if only lines 107-110 should be removed or anything else too?

**Comment by alexcrichton** [comment]
@ljedrz yes this should be published

**Comment by ljedrz** [comment]
Can you please advise if only lines 107-110 should be removed or anything else too?

**Comment by alexcrichton** [comment]
Yes those can probably be removed now, unsure about others. Best way to find out is to test it!
