### ISSUE TITLE
Does macOS frameworks supported?

### ISSUE THREAD

**Issue by RazrFalcon** [alexcrichton/cc-rs#273]
I'm trying to link Qt to my project and trying to mimic `qmake` behavior, but it uses the `-F` flag for frameworks. Can I set it in `cc`?

And can I link frameworks via rustc at all?

**Comment by alexcrichton** [comment]
A flag may be missing today but one could certainly be added!

**Comment by RazrFalcon** [comment]
I'm using `Build::flag` flag for now. But a specific option will be great.

**Comment by alexcrichton** [comment]
For now I think expliclty passing flags is good enough for this, but a PR is always fine to add new features if necessary.
