### ISSUE TITLE
Expose is_flag_supported

### ISSUE THREAD

**Issue by kornelski** [alexcrichton/cc-rs#277]
Would it be possible to expose `is_flag_supported` in the public API?

I want to set `-march={}`, but the compiler may be older than the desired target architecture and reject it. I can't just use `flag_if_supported`, because if the flag is rejected, I don't want to ignore it. I want to set other flags as a fallback instead, and the fallback flags shouldn't be set unconditionally. (related to #268)

**Comment by alexcrichton** [comment]
Seems plausible to me!
