### ISSUE TITLE
Don't pass -ffunction-sections or -fdata-sections on Darwin targets

### ISSUE THREAD

**Issue by comex** [alexcrichton/cc-rs#291]
On GNU targets, these flags are necessary to allow the linker to strip unused symbols.  On Darwin, they aren't necessary for that, and in fact don't seem to have any effect.  Normally they're harmless, but if the user passes `-fembed-bitcode` in CFLAGS, Xcode's version of clang gets upset:

```
clang: error: -ffunction-sections is not supported with -fembed-bitcode
clang: error: -fdata-sections is not supported with -fembed-bitcode
```

Thus, it would be best to simply omit these flags on Darwin.

**Comment by alexcrichton** [comment]
Sounds reasonable to me!
