### ISSUE TITLE
stderr leaked during Windows build of openssl crate

### ISSUE THREAD

**Issue by johnthagen** [alexcrichton/cc-rs#296]
Originally reported at https://github.com/sfackler/rust-openssl/issues/735

On Windows 10 x64, using this OpenSSL installer: https://slproweb.com/download/Win64OpenSSL-1_1_0f.exe

A warning is printed during cargo build

```
rust-openssl\openssl> cargo build
   Compiling vcpkg v0.2.2
   Compiling foreign-types v0.2.0
   Compiling libc v0.2.31
   Compiling bitflags v0.9.1
   Compiling lazy_static v0.2.8
   Compiling pkg-config v0.3.9
   Compiling openssl v0.9.18 (rust-openssl/openssl)
   Compiling cc v1.0.0
   Compiling openssl-sys v0.9.18 (rust-openssl/openssl-sys)
warning: expando.c
    Finished dev [unoptimized + debuginfo] target(s) in 10.89 secs
```

@alexcrichton wrote:

> I think this has to do with cl.exe /E where the cl.exe typically prints the filenames its compiling to stdout but using /E I think switches that to stderr. We should probably suppress the output here in the cc crate and not print stderr by default in these situations.

**Comment by alexcrichton** [comment]
I'm going to close this since I don't think it comes up all that frequently and otherwise I would prefer to not tamper with the output of the C compilers too much.
