### ISSUE TITLE
If CC="..." has leading or trailing space, cc fails with e.g. "Internal error occurred: Failed to find tool. Is `gcc ` installed?"

### ISSUE THREAD

**Issue by dholbert** [alexcrichton/cc-rs#297]
(Note: I'm using libloading 0.5 in my STR, as a simple example client of this `cc` library - I suspect you can trigger this without a helper library too, but I'm new to rust/cargo/crates/etc. so I don't have STR like that at this point).

STR: run the following commands:
````
mkdir /tmp/my-project
cd /tmp/my-project
cargo init
echo libloading = \"0.5\" | tee -a Cargo.toml
CC=" gcc" cargo build
````
(note the trailing space character after "CC". Doesn't matter if you use clang or gcc, or the absolute path like /usr/bin/gcc -- just be sure to include a stray space character.)

ACTUAL RESULTS:
Build error like this:
````
   Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling cc v1.0.6
   Compiling libloading v0.5.0
error: failed to run custom build command for `libloading v0.5.0`
process didn't exit successfully: `/scratch/work/builds/foo/target/debug/build/libloading-b2ddd3400b9c6044/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=dl
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some(" gcc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: " gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/scratch/work/builds/foo/target/debug/build/libloading-b737b93dbca2dfac/out/src/os/unix/global_static.o" "-c" "src/os/unix/global_static.c"

--- stderr
thread 'main' panicked at '

Internal error occurred: Failed to find tool. Is ` gcc` installed?

', /home/dholbert/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.6/src/lib.rs:2043:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
````

**Comment by dholbert** [comment]
EXPECTED RESULTS:
`cc` should strip leading & trailing space from the CC variable before running it as a binary

**Comment by dholbert** [comment]
Note: this issue is currently preventing me from building mozilla-central.  I have CC=clang in my .bash_aliases, but something in the mozilla-central build process is expanding that to `CC = " /usr/bin/clang"` (note the leading space) by the time we get to compiling `libloading`. And then my build errors out with error output like what I listed in comment 0.

**Comment by dholbert** [comment]
(thanks to @emilio for helping me get to the bottom of this!)
@alexcrichton, do you have cycles to take a look at this?  I'm not sure how easy it is to trigger, but it broke my mozilla-central build on two different machines today -- though I don't yet know what's repsonsible for inserting the problematic space into the `CC` variable, and I haven't heard of anyone else affected by this yet. But I suspect it might affect at least a handful of developers, once other people pull in updated mozilla-central and get the libloading/cc dependency.

(Also, FWIW: mozilla-central itself handles whitespace on `$CC` gracefully. If I manually do e.g. `export CC="   /usr/bin/clang  "` with lots of whitespace, and then try to build mozilla-central, we can still compile C code just fine -- we seem to strip off the whitespace as part of the initial build steps.  For example, I see this in my output, with whitespace stripped away:
> checking whether /usr/bin/clang -std=gnu99 accepts -pthread... yes

**Comment by alexcrichton** [comment]
Certainly! Not too bad of a patch :)

**Comment by dholbert** [comment]
Thanks! With your version bump, I can confirm that my minimal STR no longer produce an error.  (I'll try rebuilding mozilla-central now & see if that's fixed too.)

**Comment by tmiasko** [comment]
Most common approach to handling CC, CFLAGS and friends is to use UNIX shell
parsing rules, essentially to retain backward compatibility with behaviour one
would get from make. In Python one would use shlex.split, in Rust you can
take a look at: https://github.com/tmiasko/shell-words#split

**Comment by dholbert** [comment]
Sadly, I don't think this will fix my mozilla-central issues after all.  Proximal issue: on my linux machine, mozilla-central apparently appends `-std=gnu99` to the end of the $CC environmental variable ([here](https://dxr.mozilla.org/mozilla-central/rev/6ff60a083701d08c52702daf50f28e8f46ae3a1c/build/moz.configure/toolchain.configure#483-489)), so I end up with something like the following:
`CC='/usr/bin/clang -std=gnu99'`

That value of CC triggers a similar problem in this crate, unfortunately:
````
Internal error occurred: Failed to find tool. Is `clang -std=gnu99` installed?
````

I think the fundamental issue here is that this "cc-rs" crate is *expecting* $CC to be the exact name of an executable, but really $CC might include some space-delimited args.  I think @tmiasko's suggestion to split $CC (at whitespace boundaries, roughly?) sounds like it might be on the right track.

**Comment by alexcrichton** [comment]
@dholbert unfortunately we try to support spaces in paths in this crate for platforms like Windows, so it's not as easy as picking up a shell interpreter. We can do some level of configuration but this can only go so far...

Mind filing a separate issue though for flags passed through `CC`?

**Comment by tmiasko** [comment]
I will also note that using shell syntax actually enables one to use whitespace
in paths and other arguments. The shell syntax is general enough to express
arbitrary sequences of arguments including those that contains whitespace.
Using it would make cc crate compatible with for example autotools, make or
meson.

Here for example current behaviour of splitting CFLAGS by whitespace, causes
problems for people working on Windows: https://github.com/alexcrichton/cc-rs/issues/80

But as a downside, you need to escape whitespace in some way, i.e., using
backslash, single quotes or double quotes. Thus Windows style paths
with spaces in CC will not work out of the box when used without any form
of escaping.

The is also a middle ground possible. Cmake for example, checks if CC as a
whole represents an existing path, if so, uses it as is. In other cases it tries
to perform more advanced argument splitting that supports both backslashes and
quotes.

**Comment by alexcrichton** [comment]
I've personally hoped to avoid picking up a shell syntax or otherwise defining a custom specification for how to pass flags down (as it varies greatly across build systems it seems), but something like cmake's logic sounds plausible to me!

**Comment by dholbert** [comment]
(I filed #300 for https://github.com/alexcrichton/cc-rs/issues/297#issuecomment-372873037 )
