### ISSUE TITLE
The automatic stdc++ linking makes it impossible to statically link stdc++ on Android

### ISSUE THREAD

**Issue by tomaka** [alexcrichton/cc-rs#310]
In order to statically link the standard C++ library, I pass `-lc++_static` to the linker by tweaking my `.cargo/config` file, like this:

```rust
[target.armv7-linux-androideabi]
linker = "arm-linux-androideabi-clang"
ar = "arm-linux-androideabi-ar"
rustflags = ["-C", "link-arg=-lc++_static", "-C", "link-arg=-lc++abi", "-C", "link-arg=-landroid_support"]

[target.arm-linux-androideabi]
linker = "arm-linux-androideabi-clang"
ar = "arm-linux-androideabi-ar"
rustflags = ["-C", "link-arg=-lc++_static", "-C", "link-arg=-lc++abi", "-C", "link-arg=-landroid_support"]
```

However `cc-rs` automatically adds `-l stdc++` at the end of the arguments because of the `cpp_link_stdlib()` method.
For an undetermined reason, this `-l stdc++` flag seems to have taken priority over `-l c++_static`, which means that compiled libraries now depend on `c++_shared`. The Android build of Parity has recently broken because of that.

Ideally there should be a way to overwrite the default value for `cpp_link_stdlib()` from the `.cargo/config.toml`, however that's not really possible.

Do you have any suggestion?

**Comment by alexcrichton** [comment]
Can `cpp_link_stdlib(None)` be used to disable passing this flag?

**Comment by tomaka** [comment]
> Can cpp_link_stdlib(None) be used to disable passing this flag?

Yes, but this would need to be done for every single library that uses `cc-rs`. I don't think it's the role of each library maintainer to decide to which stdc++ to link to.

**Comment by alexcrichton** [comment]
I think at this point yeah that's what it amounts to unfortunately. Nothing works in isolation without linking the standard library.

One other possible alternative would be some sort of env var which cc recognizes and tweaks by default
