### ISSUE TITLE
Don’t enable warnings by default

### ISSUE THREAD

**Issue by SimonSapin** [alexcrichton/cc-rs#312]
https://docs.rs/cc/1.0.10/cc/struct.Build.html#method.warnings says “Enabled by default.”

These warnings typically go into a Cargo build script log that is not shown as long as compilation succeeds. When compilation fails however, the relevant parts of that log (errors) are often hard to find in a large amount unrelated warnings.

What was the reason for enabling warnings by default?

**Comment by alexcrichton** [comment]
There's some more discussion at https://github.com/alexcrichton/cc-rs/issues/237, but the tl;dr; is that `cc`-the-crate is primarily intended for compiling your own C code rather than foreign C code. While it helps with the latter it's thought to be a much smaller set than the former.
