### ISSUE TITLE
Honor CROSS_COMPILE environment variable for all tools

### ISSUE THREAD

**Issue by athei** [alexcrichton/cc-rs#319]
I am trying to cross compile a library (ring) for arm using a crosstool-ng generated C compiler by emitting this command:
`PATH=/Volumes/toolchain-arm/arm-unknown-linux-musleabi/bin:$PATH CROSS_COMPILE=arm-unknown-linux-musleabi- CC=arm-unknown-linux-musleabi-gcc cargo build --target arm-unknown-linux-musleabi`

It seems that CROSS_COMPILE is ignored because I get this warning which indicates that the system ranlib is used:
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: warning for library: /Users/alex/Downloads/ring/target/arm-unknown-linux-musleabi/debug/build/ring-12afce7c92a7c807/out/libring-core.a the table of contents is empty (no object file members in the library define global symbols)`

Is it possible so somehow improve the cross compile support by honoring the CROSS_COMPILE prefix?

**Comment by alexcrichton** [comment]
Sounds reasonable to me!

**Comment by alexcrichton** [comment]
I'm going to close this since it doesn't seem too too pressing a year on. I think it's fine to send a PR to support this here, but otherwise having a stale issue I don't think is helping this get added any more quickly!
