### ISSUE TITLE
Expose the ability to extend cc with different compilers/tool families

### ISSUE THREAD

**Issue by ZerothLaw** [alexcrichton/cc-rs#327]
Example: C# library that exports methods via COM

My situation: 
I'm working on a library to load and call .Net/CLR code via a hosted .Net runtime. Part of the hosting code requires a .Net library be built and exposed (via a type library) to C/C++. 

It'd be nice if I could add a custom compiler (csc.exe for this example) and pass custom flags via .flags and env vars.

**Comment by alexcrichton** [comment]
I'm going to close this for now since I think this is out of the purview of this project. This isn't really intended to be a one-stop-shop to compile everything under the sun but rather abstracting over the main differences between compiling C/C++ across major platforms.
