### ISSUE TITLE
Strip out -v from compile flags when checking if a flag is supported

### ISSUE THREAD

**Issue by jdm** [alexcrichton/cc-rs#329]
If `-v` is present in CFLAGS/CXXFLAGS during the compilation check to see if a given flag is supported, this makes `clang` add information to stderr that is not actually an error. This means that we get erroneous and extremely confusing results when usually the presence of `-v` means that we're trying to debug something in a native build.

**Comment by alexcrichton** [comment]
Sounds reasonable to me! I'd definitely merge a PR doing this!
