### ISSUE TITLE
Use a prefixed archiver if using a prefixed compiler

### ISSUE THREAD

**Issue by japaric** [alexcrichton/cc-rs#330]
Original report: https://github.com/japaric/cortex-m-rt/issues/80

We are using `cc` to cross assemble some external ARM assembly files for the `thumbv*` targets. `cc` uses by default `arm-none-eabi-gcc` as the assembler and `ar` as the archiver and that works fine on Linux. But on Windows `ar` is usually not available; however, the user will have `arm-none-eabi-ar` installed because they installed `arm-none-eabi-gcc`.

Could we make `cc` use `$prefix-ar` if `$prefix-gcc` is being used for compiling / assembling? `ar` doesn't do anything architecture specific so using `ar` or `$prefix-ar` would give the same results but it's more likely that user has `$prefix-ar` installed if they have `$prefix-gcc` installed.

**Comment by jonathanpallant** [comment]
I fell over this today :/
