### ISSUE TITLE
Non-bin crate with a binary

### ISSUE THREAD

**Issue by kornelski** [alexcrichton/cc-rs#340]
On [crates.rs](https://crates.rs/crates/cc) I'm trying to highlight which crates have binaries. 

Soon, for "app-like" crates, I'm planning to show install instructions that tell to use `cargo install` rather than updating `[dependencies]`.

This crate is one of the exceptions — it has a binary, but the binary is internal and not supposed to be used.

I don't see any way to distinguish "real" and "internal" binaries based on `Cargo.toml` and other data in the crate. Do you have any suggestions?

**Comment by alexcrichton** [comment]
One possible heuristic would be dependency edges possibly? This crate has a lot of crates depending on it so it could be auto-classified as a library (apps shouldn't have much or anything depending on them in theory)

**Comment by kornelski** [comment]
That'd be doable, but then I'd be worried about missing bin part of crates that are both bin and lib.

Could Cargo.toml have something like `[[bin]] private = true`? Or crates.io expose download numbers for `cargo install` separately from downloads of dependencies?

**Comment by alexcrichton** [comment]
That's plausible yeah, but I think Cargo would issue warnings about an unused manifest key for that?

Unfortuantely right now there's no way to distinguish `cargo install` from normal cargo downloads, but that doesn't mean it couldn't be added!

**Comment by kornelski** [comment]
I've went for the dependency graph workaround. Thanks!
