### ISSUE TITLE
Support setting target-features and target-cpu

### ISSUE THREAD

**Issue by gnzlbg** [alexcrichton/cc-rs#344]
It would be great to have a way to be able to forward enabled Rust target features down to the C and C++ compilers, mapping the Rust names to the C / C++ compiler names depending on the compiler being used (for clang and gcc these names should be identical to the Rust ones most of the time).

The same applies to the target CPU where different compilers use `-mcpu`/`-march`/... to set it.

**Comment by alexcrichton** [comment]
Seems reasonable to me!

**Comment by alexcrichton** [comment]
I'm actually going to close this in favor of https://github.com/alexcrichton/cc-rs/issues/268
