### ISSUE TITLE
Query compiler name and version

### ISSUE THREAD

**Issue by gnzlbg** [alexcrichton/cc-rs#345]
Is it possible to query the compiler name and version?

For cross-language inlining I need clang > 7, and to pass `-flto=thin` when compiling C and C++ code.

However, clang 4, 5, and 6 also support `-flto=thin`, so I can't really use `.is_flag_supported` to reliably detect this.

**Comment by gnzlbg** [comment]
cc @michaelwoerister is firefox doing this via the cc-rs crate ? If so, could you point me to the relevant source code?

**Comment by alexcrichton** [comment]
Currently the pathname can be queried, but the version would need to be queried manually by extracting a `Tool` and passing arguments manually.

**Comment by luser** [comment]
> cc @michaelwoerister is firefox doing this via the cc-rs crate ? If so, could you point me to the relevant source code?

No, the Firefox build does this in some Python code in our configure step:
https://searchfox.org/mozilla-central/rev/c07aaf12f13037c1f5a343d31f8291549e57373f/build/moz.configure/toolchain.configure#437-571

sccache has some Rust code for detecting compiler types, but not version numbers:
https://github.com/mozilla/sccache/blob/05bd9c7944d8c7c6e11f994c8cb5246f7638d887/src/compiler/compiler.rs#L867-L958

Feel free to borrow code from either of those, though!

**Comment by alexcrichton** [comment]
I'm going to close this since I'd rather leave this deferred to consumers rather than built-in to this crate itself.

**Comment by gnzlbg** [comment]
Does that mean that a different crate should handle `linker-plugin-lto=on` when available ?

**Comment by alexcrichton** [comment]
Presumably yeah
