### ISSUE TITLE
Can not use cc in projects located at a path with a space in it on Windows (using msvc)

### ISSUE THREAD

**Issue by tinco** [alexcrichton/cc-rs#348]
I found this bug whilst trying to compile `rustlang/rust` on Windows. It crashes because something goes wrong with the prefix for the include directories. In `cc-rs` it crashes with a slightly different error:

```
NMAKE : fatal error U1071: cycle in dependency tree for target 'C:\source\a'
```

This is easily reproduced like so:

```
cd ..
md -Path "a a"
mv cc-rs "a a"
cd "a a/cc-rs/cc-test"
cargo build
```

I tried to make a test for this, but I failed, apparently it's not a bug in the way the `.include()` method works as including paths with a space in it works fine. It must have to do something with the way the project prefix is made or used.

**Comment by tinco** [comment]
Related rustlang issue is here: https://github.com/rust-lang/rust/pull/52319

**Comment by alexcrichton** [comment]
Thanks for the report! That issue does seems whitespace related yeah but I can't quite tell myself unfortunately what the bug is or how it'd be fixed :(

The issue could also just be with rust-lang/rust and various submodules it builds there, but I'm not so sure.

**Comment by alexcrichton** [comment]
I think the issue you're seeing is definitely a bug in `cc-rs`'s own tests, but I don't think it's the same bug that you were seeing in rustc. The issue here is with NMake and spaces-in-paths, which is pretty different from using `cc::Build` to invoke C/C++ compilers

**Comment by alexcrichton** [comment]
Ah unfortunately not that I know of :(

I was under the impression we correctly handled this everywhere...

**Comment by alexcrichton** [comment]
I'm going to close this since I think it's just an internal bug in this crate's test suite, and I think we're probably just going to say "that doesn't work", but a PR to fix it is always welcome!
