### ISSUE TITLE
Link gcc crate to here

### ISSUE THREAD

**Issue by duncanfinney** [alexcrichton/cc-rs#353]
A lot of the examples and stuff link to the `gcc` crate that hasn't been updated for a while. 

https://crates.io/crates/gcc

It would be cool if the README for that crate pointed to the `cc` crate.

**Comment by alexcrichton** [comment]
A good idea! I've published a new version with the deprecation notice

**Comment by duncanfinney** [comment]
> A good idea! I've published a new version with the deprecation notice

That's crazy fast turnaround time. Thanks! 👍
