### ISSUE TITLE
Add support for nvidia cuda toolkit

### ISSUE THREAD

**Issue by lumasepa** [alexcrichton/cc-rs#355]
In the README says

```cc-rs also supports compiling CUDA C++ libraries by using the cuda method on Build (currently for GNU/Clang toolchains only)```

I would like to add support for nvidia cuda toolkit using the `nvcc` compiler to compile `.cu` files to a static library. 

Do you think that it fits in this project?
And in case that it fits, what do you think that is the best way to make it fit?

**Comment by alexcrichton** [comment]
Sure! If it's not too much code it seems fine to include here.

**Comment by alexcrichton** [comment]
I think this has since been added, so I'm going to close.
