### ISSUE TITLE
Add support for the nasm assembler

### ISSUE THREAD

**Issue by lu-zero** [alexcrichton/cc-rs#356]
Hopefully adding support for it shouldn't be overly intrusive.

**Comment by alexcrichton** [comment]
I'm going to close this since I don't think it's something we're going to want to add here. It's always possible to call nasm directly in a build script and I don't think that this crate would really offer too much over doing that.

**Comment by lu-zero** [comment]
The nearly-orphaned nasm-rs crate duplicates a good deal of the same logic present in cc-rs so I was planning to move the nasm-specific bits and avoid it since we have to use nasm for x86 and as for arm.
