### ISSUE TITLE
Simplify usage outside build script

### ISSUE THREAD

**Issue by RReverser** [alexcrichton/cc-rs#368]
Currently cc heavily relies on environment variables to determine default host, target and other compiler params. This makes it hard to use outside build script as part of normal runtime code, especially because Cargo provides such env variables exclusively to build scripts and not even to `env!` macro in regular code.

In fact, the only reasonable workaround I found is to use a build script to generate a Rust file containing all needed env vars as constants and then to include that back in a file calling `cc::Builder::new()`.

This works, but a bit cumbersome. So, I wondered if `cc` would be open to including same workaround inside its own build script so that all defaults would "just work" in any callsite, not just in other build scripts.

**Comment by alexcrichton** [comment]
There's currently builder-style methods to configure all the various env vars, but making it easier seems reasonable to me!

**Comment by luser** [comment]
Specifying those options manually is possible, see the usage in sccache tests here:
https://github.com/mozilla/sccache/blob/05bd9c7944d8c7c6e11f994c8cb5246f7638d887/tests/system.rs#L304-L319

**Comment by RReverser** [comment]
Yes, it's absolutely possible to *specify* then manually which is what I'm doing / have to do anyway, but not *detecting* which is harder to do without a build script and is something that feels like `cc` could help with by default.

**Comment by alexcrichton** [comment]
I'm going to close this since it's not a goal for this crate but PRs are of course always welcome if someone has suggestions for how to support this!
