### ISSUE TITLE
"Undefined symbols"-Error only when building with rust

### ISSUE THREAD

**Issue by JulianWels** [alexcrichton/cc-rs#372]
I've got a super small cpp file which basically just contains some OpenCV calls:
```cpp
#include <opencv2/opencv.hpp>

extern "C"
void example(uint32_t width, uint32_t height, uint8_t* data) {
    auto image = cv::Mat(cv::Size(width, height), cv::CV_8UC3, data);
    /** other stuff */
}
```
Which actually compiles when I call `gcc` manually. It also compiles with cc-rs as long as I don't make any calls to `resize_image(...)` within my rust file, but as soon as I do, "Undefined symbols" errors start showing up:

```
Undefined symbols for architecture x86_64:
    "cv::Mat::deallocate()", referenced from:
      cv::Mat::release() in libptbd_export-24f57485ccdde53d.rlib(png_resize.o)
    "cv::fastFree(void*)", referenced from:
      cv::Mat::~Mat() in libptbd_export-24f57485ccdde53d.rlib(png_resize.o)
    ( ... )
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I set almost exactly the same arguments in my `build.rs` file as I do when calling `gcc` manually.

Why could it be that it compiles manually but not with cc-rs?

**Comment by alexcrichton** [comment]
Thanks for the report! This is likely a missing library that needs to be linked and not a bug in this crate. You'll want to find the nae of the opencv library and print that in the build script for rustc to link later.
