### ISSUE TITLE
Add support for locating UWP versions of the CRT

### ISSUE THREAD

**Issue by ArmsOfSorrow** [alexcrichton/cc-rs#375]
I was told the compiler uses this crate to locate the CRT on Windows (MSVC) which is linked at the end of the build.
For UWP support it is needed to link a different version of the CRT, so I'd like to add this functionality.

I'd appreciate some guidance on where to start, since I'm not familiar with this codebase.

**Comment by alexcrichton** [comment]
This definitely seems appropriate for this crate! I think support would go around [this file](https://github.com/alexcrichton/cc-rs/blob/master/src/windows_registry.rs), and the specifics depend on how this is actually found on Windows systems

**Comment by alexcrichton** [comment]
I'm going to close this since unfortunately I don't have a ton of time to maintain more APIs in this crate, but having this in an external crate would likely work great!
