### ISSUE TITLE
1.0.30 contains a change that makes it hard to add flags such as `-mno-thumb`

### ISSUE THREAD

**Issue by eranrund** [alexcrichton/cc-rs#380]
Hi!

https://github.com/alexcrichton/cc-rs/commit/c694baec336a49ede0f55703337e3cb97f6bd728#diff-b4aea3e418ccdb71239b96952d9cddb6R1110 makes it much harder to add flags such as `-mno-thumb`. We need that for iOS compilations for armv7/armv7s targets. With cc 1.0.29 we had no problems adding it via `CFLAGS` but with 1.0.30 this gets tricky because it automatically disables the default flags, which we need.

Thanks!

**Comment by alexcrichton** [comment]
Thanks for the report! I've partially reverted the change that caused issues here which should hopefully fix the build, mind trying out 1.0.31 to confirm?

**Comment by eranrund** [comment]
That did it! Thank you so much for the amazingly fast response time!!
