### ISSUE TITLE
Allow to use something else than lib.exe to create libraries on Windows

### ISSUE THREAD

**Issue by glandium** [alexcrichton/cc-rs#384]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1537643

`LIB` is however a variable that already has a meaning, so it can't be used. The Gecko build system, as well as some other build systems tend to call it `AR` because lib.exe actually does create ar archives.

**Comment by glandium** [comment]
(although it doesn't have the same flags as unix ar)

**Comment by alexcrichton** [comment]
Using `AR` for this (and supporting that at all for other platforms) sounds pretty reasonable to me!

**Comment by glandium** [comment]
I'm not sure what you mean wrt other platforms, get_ar already reads the `AR` environment variable for them.

**Comment by alexcrichton** [comment]
Oh oops I forgot that was already supported, in that case I think it just needs to be extended to MSVC!
