### ISSUE TITLE
Strongly typed targets

### ISSUE THREAD

**Issue by GeorgeHahn** [alexcrichton/cc-rs#390]
What do you think about using [CraneStation/target-lexicon](https://github.com/CraneStation/target-lexicon) for target parsing? This looks like a very reasonably written library that would allow for replacing the target string checking code with strongly typed checks against a [`Triple`](https://docs.rs/target-lexicon/0.4.0/target_lexicon/struct.Triple.html) struct.

I would be happy to contribute this if you like the idea.

**Comment by alexcrichton** [comment]
An interesting idea! I don't think we'd benefit too much from it though in the sense that the string based checks have stood the test of time well and work reasonable enough for this crate. Perhaps some other build scripts would benefit though!
