### ISSUE TITLE
backtrace fails with minimum supported Rust version (1.16)

### ISSUE THREAD

**Issue by spl** [alexcrichton/cc-rs#422]
The “Minimum Rust (Linux)” and “Minimum Rust (Windows)” jobs on Azure keep failing with:

```
Compiling backtrace v0.3.33
error: expected identifier, found keyword `crate`
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.33/src/lib.rs:76:9
   |
76 | pub use crate::backtrace::{trace_unsynchronized, Frame};
   |         ^^^^^

error: aborting due to previous error

error: Could not compile `backtrace`.
```

Is there any way to fix this (e.g. only on Azure or in the `Cargo.toml`) or to work around it?

**Comment by alexcrichton** [comment]
Ah it's fine to bump it to 1.32.0 in that case, feel free to send a PR!

**Comment by alexcrichton** [comment]
I'm gonna close this since I don't think this is related to this crate, but PRs are always welcome to the backtrace crate!
