### ISSUE TITLE
Can we let rust to pick up the latest cc-rs?

### ISSUE THREAD

**Issue by BaoshanPang** [alexcrichton/cc-rs#423]
Hi Alex,

I am seeing the rust(in bootstrap/cargo.toml) is still using version 1.0.35, can we let rust to use the latest cc-rs?

Thanks,
Baoshan

**Comment by alexcrichton** [comment]
Yep! Sometimes it just lags but a `cargo +nightly update -p cc` should do the trick!

**Comment by BaoshanPang** [comment]
Hi Alex,
Thanks for the quick response.
I can see 1.0.37 is used after using command "cargo +nightly update -p cc", but it still don't have my code for vxWorks, will it show up in next release(1.0.38)?

Thanks,
Baoshan

**Comment by alexcrichton** [comment]
Oh oops sorry about that! I've published 1.0.38 now with the changes

**Comment by BaoshanPang** [comment]
Thanks!

**Comment by BaoshanPang** [comment]
Do we have a schedule to use the version 1.0.38(or any newer version) by default?

**Comment by alexcrichton** [comment]
We don't have a schedule for updates, no, but if you need an update feel free to send a PR to rust-lang/rust which updates `Cargo.lock`
