### ISSUE TITLE
Support for building host tools using cc-rs

### ISSUE THREAD

**Issue by kinnison** [alexcrichton/cc-rs#434]
Hi,

Sometimes it is necessary to build a set of C files for the `HOST` into a binary, and then run that binary to generate new source which will be built for the `TARGET`.

I can't quite work out how I'd do that with `cc-rs` -- is this a feature which needs writing, merely documenting, or is this the jurisdiction of another crate I've not found?

Whichever the answer, I'd be interested in making it possible and/or clearer how to achieve it in `cc-rs`'s documentation.

Thanks,

Daniel.

**Comment by alexcrichton** [comment]
Thanks for the report! I've decided over time though that creating binaries is not something I'd like to support in this crate. I'd be more than willing to ensure there's support in this crate though for a different crate to build on!

**Comment by kinnison** [comment]
That's fair, thank you for taking the time to respond.  I'll have a think about what it'd take if and when I get to needing this, and then come back to you with a request if needed :D
