### ISSUE TITLE
cc 1.0.42 with "parallel" feature hangs on Windows

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [alexcrichton/cc-rs#440]
### To reproduce
1. `cargo new --bin сс_jobserver`
    `cd cc_jobserver`
2. In `Cargo.toml`, put the following:
    ```
    [dependencies]
    rusqlite = { version = "*", features = ["bundled"] }
    zstd = { version = "*", default-features = false }
    ```
    (my [`Cargo.lock`](https://gist.github.com/Vlad-Shcherbina/73260d7a7821275a5b4463109752a714) if you want to reproduce perfectly)
3. `cargo build`

### Expected result
Build completes in finite time.

### Actual result
The build hangs in the following state:
```
> cargo build
    Updating crates.io index
   Compiling log v0.4.8
   Compiling getrandom v0.1.12
   Compiling jobserver v0.1.17
   Compiling cc v1.0.42
   Compiling zstd-sys v1.4.13+zstd.1.4.3
   Compiling libsqlite3-sys v0.16.0
    Building [============================================>            ] 32/40: zstd-sys(build), libsqlite3-sys(bu...
```
The process tree looks like this:
![image](https://user-images.githubusercontent.com/302938/64464618-4c85d800-d111-11e9-8576-cbcdb0b87265.png)

These two `build-script-build.exe` don't use CPU and don't make any progress.

----------------

I think this is related to `cc 1.0.42` because first, if I pin `cc` to `1.0.41`, it builds successfully, and second, because there was this change: https://github.com/alexcrichton/cc-rs/commit/4fda8db89e666f402392366501505a4fbd14b23f .

---------------

Version info:
```
> cargo --version --verbose
cargo 1.39.0-nightly (3f700ec43 2019-08-19)
release: 1.39.0
commit-hash: 3f700ec43ce72305eb5315cfc710681f3469d4b4
commit-date: 2019-08-19

rustc --version --verbose
rustc 1.39.0-nightly (521d78407 2019-08-25)
binary: rustc
commit-hash: 521d78407471cb78e9bbf47160f6aa23047ac499
commit-date: 2019-08-25
host: x86_64-pc-windows-msvc
release: 1.39.0-nightly
LLVM version: 9.0
```

I observe this problem on a machine with 2 cores.

**Comment by alexcrichton** [comment]
Oops sorry about that! Should be fixed in https://github.com/alexcrichton/cc-rs/commit/238ee4f093c37084314711f05154c14eb6362711

**Comment by Vlad-Shcherbina** [comment]
Thank you. I confirm it appears to work fine with `cc 1.0.45`.
