### ISSUE TITLE
Tests fail under Gentoo build environment: "x86_64-pc-linux-gnu-gcc" != "cc"

### ISSUE THREAD

**Issue by kentfredric** [alexcrichton/cc-rs#444]
```

     Running `/var/tmp/portage/dev-rust/cc-1.0.38/work/debug/deps/cc_env-7283ef0126320fed`

running 1 test
test main ... FAILED

failures:

---- main stdout ----
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = Some("x86_64-pc-linux-gnu-gcc")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = Some("-O2 -pipe -mtune=native -march=native")
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = None
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"x86_64-pc-linux-gnu-gcc"`,
 right: `"cc"`', tests/cc_env.rs:29:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    main

```

```
grep 'declare.*CC' '/var/tmp/portage/dev-rust/cc-1.0.38/temp/environment'
declare -x GCC_COLORS="error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01"
declare -x GCC_SPECS=""
declare -x HOST_CC="x86_64-pc-linux-gnu-gcc"
declare -x TARGET_CC="x86_64-pc-linux-gnu-gcc"
```

**Comment by alexcrichton** [comment]
Thanks for the report! The tests aren't really robust to running in any arbitrary environment, they don't sanitize a bunch and assume they're running in a clean environment. I don't mind taking PRs to fix tests but this isn't something I'd consider a bug in the crate so I'm going to close this.

**Comment by kentfredric** [comment]
The thing with this apparent mindset, is that having some level of drive to encourage some consumer audience to run tests, by way of having no spurious test failures, ends up in your benefit in the long term, because it encourages the exposure of *real* problems.

And the rust-ecosystem at large benefits from this.

As a linux-vendor maintainer, being able to run tests improves the overall guarantees of quality I can deliver for users, and helps me help upstream in keeping everything working nicely.

In this specific situation, I don't know enough about "your code" to work out where the fix should be applied, or how, so some general direction would be helpful if you honestly anticipate I might file a PR.
