### ISSUE TITLE
wasm32-unknown-unknown target build error for LLVM 8 on macOS

### ISSUE THREAD

**Issue by xxuejie** [alexcrichton/cc-rs#447]
The error can be located at here: https://travis-ci.com/nervosnetwork/ckb-standalone-debugger/jobs/244224772/

I don't have a working macOS installation now, but since the error happens when you are building LLVM 8, I suspect the following steps should reproduce it:

```
$ brew install llvm@8
$ export PATH=/usr/local/opt/llvm@8/bin:$PATH
$ git clone https://github.com/nervosnetwork/blake2b-rs
$ cd blake2b-rs
$ cargo build --target=wasm32-unknown-unknown
```

This issue only happens on macOS. It works without problems on Linux, and if we use LLVM 9+, we would hit #446 

Any idea what the reason for this might be? Thanks in advance!

**Comment by alexcrichton** [comment]
Thanks for the report! This is a local compilation issue with wasm/LLVM that needs to be worked out though and unfortunately this isn't a great forum to debug compilation issues with. For the best results you'll want to use Clang 9 and probably the wasm32-wasi target, though.
