### ISSUE TITLE
Automatically include emscripten libc headers when building on wasm32 targets

### ISSUE THREAD

**Issue by lopopolo** [alexcrichton/cc-rs#451]
Currently, to build a sys crate with `cc` for for wasm32-unknown-emscripten and wasm32-unknown-unknown targets, it is necessary to vendor a copy of the emscripten libc headers for each crate using `cc` in its `build.rs`.

This also requires adding an explicit include path to pick up these headers.

Doing so results in lots of macro redefinition warnings.

Is it possible to replace the `-isystem` include path with emscripten headers when building wasm32 targets? This would make it much easier to support these targets and would not require forking each sys crate I depend on.

**Comment by alexcrichton** [comment]
Thanks for the report! This is unfortunately work I'm not willing to do though. In general this crate purely tries to hook up existing system toolchains with Rust code. There's a ton of thorny questions in trying to vendor/include headers for targets, so I'd prefer to not do that.
