### ISSUE TITLE
Import macOS SDK headers by default

### ISSUE THREAD

**Issue by eoger** [alexcrichton/cc-rs#452]
This problem is reproducible on macOS Catalina 10.14.6 w/ XCode 11.1.0 (latest versions at this time) and no copied headers (see more at the end of this post).

Try to `cargo build` anything that imports a system header such as `errno.h` or `pthread.h`, for example [libloading](https://github.com/nagisa/rust_libloading/blob/master/src/os/unix/global_static.c).

You will get the following:

```
Failed to run custom build command for `libloading v0.5.2`
        'pthread.h' file not found
```

On the previous version of macOS (Mojave), you could run `macOS_SDK_headers_for_macOS_10.14.pkg` that roughly copied a bunch of header files from `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include` to `/usr/include/` (reference [here](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624))
This used to fix the "file not found" problem, however this does not work anymore.
For this bug to be reproduced, these header files **must not** be present in `/usr/include`.

I believe correct solution would be for `cc` to always include `$(xcode-select -print-path)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include` on darwin target. Thoughts?

**Comment by alexcrichton** [comment]
Does the bare `clang` executable not work by default any more? I thought it's expected for them to be buried elsewhere but I also thought the default `clang` executable still worked

**Comment by eoger** [comment]
Turns out this only happens when compiling for iOS targets, I'll keep digging.

**Comment by eoger** [comment]
Found the problem! Xcode was messing up with `PATH` and I'm guessing picking up the wrong clang?
