### ISSUE TITLE
Implement `std::error::Error` for `Error`

### ISSUE THREAD

**Issue by KizzyCode** [alexcrichton/cc-rs#456]
Hey, is it possible to implement `std::error::Error` for the `Error` type? I have some parts where I want to simplify my errors into a `Box<dyn Error + 'static>`.

Since `Debug` and `Display` are already implemented and this library always uses `std`, the empty trait implementation `impl std::error::Error for Error {}` should be completely sufficient and would not break anything?

**Comment by alexcrichton** [comment]
Sounds reasonable to me to add!
