### ISSUE TITLE
--target on FreeBSD with default target breaks clang++

### ISSUE THREAD

**Issue by myfreeweb** [alexcrichton/cc-rs#463]
As I understand, the default (???) `--target` value comes from Rust/Cargo. It ends up as something like `x86_64-unknown-freebsd`. Passing that to clang++ breaks everything (causes it to look for gnu stdc++, not to look for C++ headers in the default location, etc.) clang++ only handles versioned FreeBSD targets (e.g. `x86_64-unknown-freebsd13.0`) correctly.

Who is to blame is a hard question — should llvm/clang be fixed to accept unversioned targets? should Rust report versioned targets? both? — but I'm not sure if the target should be passed at all when not cross-compiling…

**Comment by myfreeweb** [comment]
hm, the same(ish) build outside of ports / with rustup rust didn't have that issue, maybe the `$TARGET` was external

**Comment by alexcrichton** [comment]
A PR to fix this would definitely be welcome!

**Comment by mqudsi** [comment]
I don't think this bug report is valid; @myfreeweb is there a repro? 

FreeBSD is our primary production target for a number of products and we've never run into this issue (including some severely stripped down configurations that definitely don't have have stdc++).

**Comment by myfreeweb** [comment]
As I said above, this only happened when building in Ports. I can't find where it would set anything like that but the problem is there, I'm pretty sure now.

**Comment by myfreeweb** [comment]
Update: we'll fix this in LLVM — https://reviews.llvm.org/D77776
