### ISSUE TITLE
disable pic for cortex-m

### ISSUE THREAD

**Issue by stepansnigirev** [alexcrichton/cc-rs#468]
According to the [documentation](https://docs.rs/cc/1.0.4/cc/struct.Build.html#method.pic) `pic` is enabled by default for all targets but `windows-gnu`.

If I understand correctly, cortex-m-rt doesn't support position-independent code (https://github.com/rust-embedded/cortex-m-rt/blob/master/link.x.in#L144). 

Would it make sense to disable `pic` by default for all cortex-m targets? (`thumbv7m-none-eabi`, `thumbv7em-none-eabihf` and similar)

I am having this problem with secp256k1 library bindings (https://github.com/rust-bitcoin/rust-secp256k1/issues/193) - I need to clone and manually change the build.rs file to make it compiled for my board...

**Comment by alexcrichton** [comment]
Sounds good to me! The documentation was written long ago when this crate supported far fewer crates, but in general this crate intends to compile code with each platform's "best practices", whatever that may be, no matter how different it is from other platforms.

**Comment by stepansnigirev** [comment]
Just wondering... Looks like riscv bare metal also doesn't support pic. Is it true for all bare metal targets?

This would mean that fixing these lines 

https://github.com/alexcrichton/cc-rs/blob/9228de68b1795e335e1e1197ef2fde9cf431e5b9/src/lib.rs#L1376-L1377 

to

```
!target.contains("windows-gnu") && !(target.contains("-none-")),
```

would do the job.

**Comment by alexcrichton** [comment]
I'm not too too certain about all the targets, but it seems plausible to try!
