### ISSUE TITLE
Building wrong Target when building for Mac Catalyst

### ISSUE THREAD

**Issue by ubamrein** [alexcrichton/cc-rs#471]
When building for mac catalyst (which is available in the rust master branch as of some time) I faced the problem that `backtrack-sys` was either trying to build for the iPhone Simulator or for MacOSX but not for the new Macabi (The `cc` crate  seems to decide based on if there is ios or darwin in the target name). In the target configuration for Xargo there is a field called `llvm-target`, which essential is the target needed to be set for the `CC`.

The problem showed up upon linking in `xcode` (or generating a xcframework), where it claimed that the platform for one of the objects in the static library (`state.o`) was not built for `Macabi`.

To circumvent the problem I could, in the end, just apply the `CFLAGS="-target x86_64-apple-ios13.0-macabi"` to the xargo build-command (where the target is as mentioned above the llvm-target specifier for the custom target configuration for Xargo), which overrides the old compiler flags and uses the correct target. I though get warnings since the previous compiler flags are ignored (related to ios e.g.)

Cheers
Patrick

**Comment by alexcrichton** [comment]
I'm not personally sure how best to detect and fix this, but a PR for this would be most welcome!

**Comment by amrx101** [comment]
@ubamrein , Did you try the idea  that you presented?

**Comment by ubamrein** [comment]
yes this worked (except for the warnings) in the end without problems. Though Apple is restrictive regarding the APIs which are exposed on Mac Catalyst/iPhone... so I never followed this lead further
