### ISSUE TITLE
Require full mingw compiler name

### ISSUE THREAD

**Issue by aristarh2704** [alexcrichton/cc-rs#474]
For supporting this crate on cygwin, crate should call full mingw compiler (i686-w64-mingw32-gcc) , not cc/gcc.
This lines should be changed: [compiler names](https://github.com/alexcrichton/cc-rs/blob/master/src/lib.rs#L1898-L1901)

**Comment by alexcrichton** [comment]
This can be configured via env vars, and otherwise the default names are chosen to match the expected native host environment, so I'm going to close this.
