### ISSUE TITLE
Provide a mechanism to link "test" binaries

### ISSUE THREAD

**Issue by jmmv** [alexcrichton/cc-rs#477]
I'm trying to check for the presence of a libc function from my `build.rs` script. This crate seems almost suitable for this purpose... except for the fact that it only builds a library. In order to check for the presence of the missing function, I actually need to *link* the code into a binary to discover the unresolved symbols.

More context in this thread: https://users.rust-lang.org/t/detecting-the-presence-of-a-system-function-at-build-time/37968

I'm filing this issue to discuss whether this feature would make sense in this crate. I can imagine a `try_link` function that attempts to build and link the given C source (and then I can just delete the resulting output). From the description, this crate seems focused on compiling a C library that is later linked into the Rust build... so this "link a test binary that's later discarded" doesn't seem to fit in spirit. But functionally, it should be rather simple to implement here.

**Comment by alexcrichton** [comment]
Thanks for the report! There's a few other closed issues with feature requests like this, but I unfortunately don't have the time/energy to maintain all the intricacies of dealing with binaries, so I'm going to close this. I'm more than willing to help such a crate exist on crates.io and depend on the `cc` crate, and `cc` may need to expose more information for that to exist.
