### ISSUE TITLE
Set ZERO_AR_DATE=1 for deterministic static libraries on macOS

### ISSUE THREAD

**Issue by luser** [alexcrichton/cc-rs#494]
Just the other day I learned that Apple's `ar` tool has an undocumented environment variable that you can use to get it to zero out timestamps so you get reproducible archives! Setting `ZERO_AR_DATE=1` apparently triggers this behavior.

Here's the source for reference:
https://opensource.apple.com/source/cctools/cctools-949.0.1/misc/libtool.c.auto.html

It's also mentioned in this LLVM blog post:
http://blog.llvm.org/2019/11/deterministic-builds-with-clang-and-lld.html

This would help fix https://github.com/mozilla/sccache/issues/169 .

**Comment by alexcrichton** [comment]
This was actually already added in https://github.com/alexcrichton/cc-rs/commit/555e7737237dda29e39308c6fc6c88cf93bc5853, although did I forget a different place we need to put that?

FWIW I didn't know this env var affected the linker, but if so then we should probably update rust-lang/rust to set this env var for the linker unconditionally.

**Comment by luser** [comment]
Oh nice! I did search the repo for issues but didn't search the code so I didn't see that. Oops!

> FWIW I didn't know this env var affected the linker, but if so then we should probably update rust-lang/rust to set this env var for the linker unconditionally.

Good point! I hadn't looked into that but apparently it makes `ld64` zero out timestamps in the `N_OSO` stabs it writes that point back to object files (that `dsymutil` uses to link debug info):
https://github.com/apple-opensource/ld64/blob/fd3feabb0a1eb18ab5d7910f3c3a5eed99cef6ab/src/ld/Options.cpp#L4420

I'll open an issue on the Rust repo for that!

**Comment by luser** [comment]
Oh you already filed one a while back and someone mentioned this there, hah:
https://github.com/rust-lang/rust/issues/47086#issuecomment-575907024
