### ISSUE TITLE
Seems I can't build from c++ (Tested both on Linux and MacOS) linker can't find `hello`.

### ISSUE THREAD

**Issue by Narsil** [alexcrichton/cc-rs#510]
I tried to add a simple header of cpp code like the C hello (https://doc.rust-lang.org/cargo/reference/build-script-examples.html).

However it seems it does not compile (it did for the C code).

Here is a link to my example.
https://github.com/Narsil/hello

I did add `.cpp(true)` to the `cc::Build`.

It seems the libfoo.a does contain the hello symbol, but somehow, it does not link correctly. Any ideas ?

**Comment by alexcrichton** [comment]
Thanks for the report, but you need to use `extern "C"` in your C++ code to avoid symbol mangling.

**Comment by Narsil** [comment]
Thanks !

Would you be accepting a PR to add this in the docs ? I could not find this, here either, maybe others would find it useful ?

**Comment by alexcrichton** [comment]
Hm this isn't necessarily related to this crate, it's more about C++ and symbol mangling. If there's a reasonable place to add makes sense, but otherwise I'm not sure there's much this crate can do about this?

**Comment by Narsil** [comment]
Tried to propose a PR (just small sentence which would have avoided some head scratching from me so possibly other ppl.) Feel free to rephrase if you think I have badly worded it.
