### ISSUE TITLE
linker parameters

### ISSUE THREAD

**Issue by pwang7** [alexcrichton/cc-rs#517]
Hi there,

Is it possible for cc-rs to specify linker parameters to `ld`?
I'm building a C library using cc-rs on MacOS, and I need to specify the `ld -framework` argument.
But if I use `flag("-framework CoreServices")`, it gave me the unknown flag error.

Thanks!

**Comment by dubiousjim** [comment]
Does `std::env::set_var("LDFLAGS", "-framework CoreServices")` work?

**Comment by pwang7** [comment]
I fixed it by using attribute `#[link(name = "CoreServices", kind = "framework")]`.
I noticed that when compiling using cc-rs in MacOS, it'll add `-emit-obj` flag to cc provided by XCode, so I think cc will only compile, not link, and it'll reject any linking flags.

**Comment by alexcrichton** [comment]
Thanks for the report! This crate, however, does not call the linker and that's up to rustc. You found one way to do it and otherwise there's also `println!("cargo:rustc-link-lib=..."` from the build script to pass `-l` arguments as well.
