### ISSUE TITLE
An option to force a specific compiler

### ISSUE THREAD

**Issue by RazrFalcon** [alexcrichton/cc-rs#541]
I'm looking for an option to force a specific compiler, like clang. So I can be sure that the code is building with the right compiler. Otherwise a user would see a nice error message.

Currently, I'm overriding the `CC` env in the `build.rs`, but I'm not sure if this is a correct way. And there is no nice error message when the compiler is actually missing.

**Comment by alexcrichton** [comment]
I believe the [`Build::compiler`](https://docs.rs/cc/1.0.58/cc/struct.Build.html#method.compiler) method should do the trick?

**Comment by RazrFalcon** [comment]
But I don't know the compiler location. Or just `clang` would work?

**Comment by nomeata** [comment]
Yes, `.compiler("clang")` did the expected thing here

**Comment by alexcrichton** [comment]
Ok, thanks!
