### ISSUE TITLE
Document CXXSTDLIB in README

### ISSUE THREAD

**Issue by alexeyr** [alexcrichton/cc-rs#559]
`CXXSTDLIB` is not currently listed in https://github.com/alexcrichton/cc-rs#external-configuration-via-environment-variables. From looking at code, I don't see any other variables which should be mentioned but aren't.

Also, I think it should not default to `stdc++` for Android, [given](https://developer.android.com/ndk/guides/cpp-support)

> On Android, libstdc++ is just new and delete. Use libc++ for a full-featured C++ standard library.
>
> Note: The system STL will be removed in a future NDK release. See Issue 744.

From the discussion in https://github.com/android/ndk/issues/744, I believe `c++_shared` should be the default; if not, `c++_static`.

**Comment by alexeyr** [comment]
I'd be happy to make a pull request.

**Comment by alexcrichton** [comment]
Indeed a PR would be great!

**Comment by alexeyr** [comment]
1. Do you have an opinion on the default Android stdlib? 

2. Would you prefer two separate PRs?

**Comment by alexcrichton** [comment]
Either way is fine by me!
