### ISSUE TITLE
vague error when `xcrun` is not present in PATH on macOS

### ISSUE THREAD

**Issue by BrianHicks** [alexcrichton/cc-rs#560]
When `xcrun` is not present in the PATH when compiling on macOS, compilation using `cc` will fail with:

```
error occurred: No such file or directory (os error 2)
```

This happened to me because I was building in Nix, which removes everything from PATH except what you explicitly specify. There's more context in this thread: https://users.rust-lang.org/t/how-can-i-determine-missing-dependencies-in-a-cargo-build-script/50199

I did a bunch of code spelunking to figure this out, but I'm a Rust newbie so I'm not sure of the best way to improve the error message. Maybe it'd be easy! I don't know!

**Comment by alexcrichton** [comment]
Thanks for the report! I think the error messsage should be a bit clearer now hopefully!

**Comment by BrianHicks** [comment]
wow, fast! Thanks a bunch! ❤️

**Comment by BrianHicks** [comment]
```
error occurred: Failed to find tool. Is `xcrun` installed?
```

Yeah, that's 100% clear and I would have been able to fix my problem in just a minute with that. Perfect!
