### ISSUE TITLE
Tool family detection is too fragile

### ISSUE THREAD

**Issue by Skirmisher** [alexcrichton/cc-rs#574]
`Tool::with_features` attempts to detect the kind of toolchain it's dealing with by doing a substring match on the compiler name. Since `cl` is not a very specific substring, the function has to work around it with exceptions to the rule:

https://github.com/alexcrichton/cc-rs/blob/8a1d5c89f02ebc58480a6e4c5b5c2aa2eb6e07c1/src/lib.rs#L2642-L2662

This obviously falls over when new exceptions appear that aren't accounted for—in this case `powerpcle`, a new target being worked on in [Void Linux](https://voidlinux-ppc.org/) at the moment. `gcc` is incorrectly detected as `cl`, so the crate passes `-nologo` to it, and ends up failing (in this case while cross-compiling the Rust toolchain).

You could of course add "powerpcle" to the list of exceptions for now, but I feel like a more robust check is warranted to avoid this situation in the future (especially when many downstreams are going to pull an old version of the crate and thus require workarounds by further-downstream packagers). Perhaps match by the end of the string, or do some separation by hyphens/underscores, at least. You could also try parsing the version output of the compiler (e.g. with regex) for a more reliable determination, though with `cl` you have to [pass it no arguments](https://stackoverflow.com/questions/1233312/finding-version-of-microsoft-c-compiler-from-command-line-for-makefiles/1233332#1233332) instead of `-v|--version`, making it a bit fiddly.

**Comment by ericonr** [comment]
Worst case, check if `compiler_command` returns an error, then try `-v`?

**Comment by alexcrichton** [comment]
Seems reasonable to me! We could also invert the ordering of tests and perhaps look for `-cl<end-of-string>` on Unix or `cl.exe` on Windows too.
