### ISSUE TITLE
Missing copyright info

### ISSUE THREAD

**Issue by atouchet** [alexcrichton/cc-rs#576]
https://github.com/alexcrichton/cc-rs/blob/417f088ec6344c6283469bdbbaec202771e4865e/src/registry.rs#L1-L3

A number of files in this repo contain this copyright info which leads to a 404 page and I do not see a COPYRIGHT file anywhere either. Is this info outdated/a mistake?

**Comment by alexcrichton** [comment]
This was copy-pasted from the rust-lang/rust project at the time. It's intended to say these files contain stuff from rust-lang/rust, which has the same license as this crate as well.

**Comment by atouchet** [comment]
Would it make sense to remove the "See the COPYRIGHT file at the top-level directory of this distribution and at http://rust-lang.org/COPYRIGHT" line in that case?

**Comment by alexcrichton** [comment]
I don't really understand the intricacies of copyright well enough to know what to do. This copied code so I copied the copyright, otherewise I don't know what needs to be done.
