### ISSUE TITLE
Building to a .wasm file

### ISSUE THREAD

**Issue by NicholasLYang** [alexcrichton/cc-rs#580]
Hi,

I'm trying to compile a C file to a .wasm file which my rust code then loads as a library in a wasmtime instance. I noticed that `cc` generally outputs a .a file. Is there a way to have it produce a .wasm file?

Thanks

**Comment by alexcrichton** [comment]
Currently, no, this library only invokes `gcc` and `ar`, it doesn't produce final linked artifacts. For that reason there's no built-in way to build a `*.wasm` file with this library.
