### ISSUE TITLE
Command "arm-none-eabi-ar" "s" "<the_output_file>.a" with args "arm-none-eabi-ar" did not execute successfully

### ISSUE THREAD

**Issue by fnune** [alexcrichton/cc-rs#587]
Hey there,

First of all, thank you for all your efforts with/for the Rust community.

I'm trying to get a library compiled that's made up of many files:

```rust
let sdk_includes = "the-library/includes";
let sdk_files = glob::glob("the-library/src/*.c");
cc::Build::new()
    .include(sdk_includes)
    .files(sdk_files.unwrap().map(|path| path.unwrap()))
    .compile("the_library_sdk");
```

This is failing with the following error:

```
cargo:warning=arm-none-eabi-ar: '[...]/out/libthe_library_sdk.a': No such file
```

I've gone through several different errors before this one and managed to fix them, and it looked like the compilation was actually happening: all of the errors had to do with missing header files or the link, which indicated to me that things were working fine.

Once I fixed all the errors related to compiling the actual library, I got this last one, and I can't figure out what's going wrong. I checked the source of `cc-rs` and I found some places where the file at `dst` gets removed, but I don't see why that should happen.

Maybe it's a matter of indirection and the actual problem lies in some other issue.

Leaving the full output here (paths edited):

```
warning: arm-none-eabi-ar: '/[...]/target/thumbv7m-none-eabi/debug/build/example-df510904a9be97f6/out/libthe_library_sdk.a': No such file

error: failed to run custom build command for `example v0.1.0 (/[...])`

Caused by:
process didn't exit successfully: `/[...]/target/debug/build/example-d483bb49e1993678/build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-changed=crate-name
TARGET = Some("thumbv7m-none-eabi")
HOST = Some("x86_64-unknown-linux-gnu")
AR_thumbv7m-none-eabi = None
AR_thumbv7m_none_eabi = None
TARGET_AR = None
AR = None
CROSS_COMPILE = None
running: "arm-none-eabi-ar" "s" "/[...]/target/thumbv7m-none-eabi/debug/build/example-df510904a9be97f6/out/libthe_library_sdk.a"
cargo:warning=arm-none-eabi-ar: '/[...]/target/thumbv7m-none-eabi/debug/build/example-df510904a9be97f6/out/libthe_library_sdk.a': No such file
exit code: 1

--- stderr


error occurred: Command "arm-none-eabi-ar" "s" "/[...]/target/thumbv7m-none-eabi/debug/build/example-df510904a9be97f6/out/libthe_library_sdk.a" with args "arm-none-eabi-ar" did not execute successfully
(status code exit code: 1).
```

**Comment by alexcrichton** [comment]
Can you check to see if that file actually exists?

If not then that's probably a bug in this crate. If so, however, it might be an issue with the toolchain that you're using.

**Comment by fnune** [comment]
Could you point me to some ways I could go about debugging underlying causes? I've read the library code but following it makes me think it should be working fine.

**Comment by alexcrichton** [comment]
Ah sorry I'm not really sure how this could come about. It may just be an edge case internally or indicative of a further bug, but in theory this library isn't too too large and it should be somewhat easy to poke around and see what's going on.

**Comment by fnune** [comment]
Ooookay, this is embarrassing: I was passing an iterator of paths that I built using `glob`, and I messed up the search and was passing `[]` to `cc-rs`.

Sorry to have wasted your time!
