### ISSUE TITLE
Is it possible to re-export symbols from C?

### ISSUE THREAD

**Issue by hanabi1224** [alexcrichton/cc-rs#590]
What I'd like to achieve is to re-export the same C symbol when I build a dylib with rust toolchain. I tried adding ```#[no_mangle]``` but it gives a warning and does not export the symbol when I check with objdump, thanks!

p.s. I know I can create another wrapper function and export that symbol but I have to give it a different name from  original C header which is not what I want.  For example if I have a lz4-sys crate, I'd like it to be able to statically link with rust code and also be able to produce dynamic library by itself (instead of building from C source code)
```rust
#[no_mangle]
pub extern fn LZ4_versionNumber() -> c_int;
```

**Comment by alexcrichton** [comment]
I think this is probably a question best for rust-lang/rust, this crate is just about building C code and linking it into you Rust project.
