### ISSUE TITLE
crash with "Illegal instruction" when build release on linux

### ISSUE THREAD

**Issue by ngoclinh93qt** [alexcrichton/cc-rs#617]
I have built the library [https://github.com/aous72/OpenJPH](url) with cc and use Bindgen to generate FFI, on Mac Os working fine when running release and debug, for Linux it's running well with debug mode, release mode  it builds success but  crashes with "Illegal instruction" when I running.
this is my Repo: [https://github.com/ngoclinh93qt/openjph-ffi](url)

**Comment by alexcrichton** [comment]
Thanks for the report but this isn't particularly actionable, do you have more information such as debug logs, system configuration, etc?
