### ISSUE TITLE
Support getting Windows SDK from the environment

### ISSUE THREAD

**Issue by ChrisDenton** [alexcrichton/cc-rs#625]
One thing that was brought up recently with the Windows CI's update was a desire to stay with a particular version of the Windows SDK even when a newer version is avaliable. Currently `cc` always gets the latest with no easy way (as far as I'm aware) to override it. Usually this works out fine but not always.

It would be great if it could default to using the environment before falling back to finding the latest. Possibly relevant environment variables (set by `vcvarsall.bat` or developer powershell):

* `WindowsSDK_ExecutablePath_x64`
* `WindowsSDK_ExecutablePath_x86`
* `WindowsSdkBinPath`
* `WindowsSdkDir`
* `WindowsSDKLibVersion`
* `WindowsSdkVerBinPath`
* `WindowsSDKVersion`

I don't have the bandwidth to test a fix for this atm, so if anyone else wants to look into it I'd appreciate it.

**Comment by ChrisDenton** [comment]
Sorry, I should have explained better. The background for this is rust-lang/rust#88796 where, at the time, using the newer Windows SDK 10.0.20348 broke whereas the older 10.0.19041 worked. I thought it would be good for cc-rs to be able to support specifying/overriding the lib version somehow.

Getting the SDK is a separate step to getting the VC install and is implemented in [fn add_sdks()](https://github.com/alexcrichton/cc-rs/blob/795a12d3809f49f2e9bf7927163c4bc5b51a4b2c/src/windows_registry.rs#L509). The version is sorted ["asciibetically"](https://github.com/alexcrichton/cc-rs/blob/main/src/windows_registry.rs#L664-L665) and only the latest is returned:

**Comment by nico-abram** [comment]
Thanks for the clarification, sent a pull request.
