### ISSUE TITLE
MSVC  = note: LINK : fatal error LNK1181: cannot open input file 'stdc++.lib'

### ISSUE THREAD

**Issue by Earthson** [alexcrichton/cc-rs#647]
```rust
    cxx_build::bridge("src/lib.rs")
        .file("src/strategyhandler.cc")
        .file("src/mquant_utils.cc")
        .flag_if_supported("/std:c++17")
        //.cpp_set_stdlib(None)
        .cpp_set_stdlib("stdc++")
        //.cpp_link_stdlib("stdc++")
        //.static_crt(true)
        .compile("run_mquant");
```

I'm not familar with C++ build, what is the correct way to link stdc++.lib on windows with MSVC?

**Comment by bugeats** [comment]
@Earthson did you figure it out? I'm trying to statically link a c++ lib on windows.

**Comment by Earthson** [comment]
> @Earthson did you figure it out? I'm trying to statically link a c++ lib on windows.

I've no idea for statically stdc++ link. I think dynamic link is fine:) just remove "stdc++" option for MSVC build.
