### ISSUE TITLE
Support out (-o) flag

### ISSUE THREAD

**Issue by naomijub** [alexcrichton/cc-rs#651]
I would like to be able to output my cpp files using the `out_dir` and  `-o` flag as:
```
include/library_name/
- cxx.h
- lib.rs.h
src/
- lib.rs.cc
bin/
- binaries.*
```

but I don't seem to have access to the `-o` flag and `out_dir` loses context of the `cxxbridge/rust/cxx.h`. The current output is:

```
cxxbridge/
- rust/
- - cxx.rs
- library_name/
- - lib.rs.h
- - lib.rs.cc
```

Is that duable?

**Comment by alexcrichton** [comment]
This library is generally intended for build scripts of Cargo, not necessarily other use cases of building C/C++ code. In that sense can you explain more why you want to control `-o` and specific output filenames?

**Comment by naomijub** [comment]
https://github.com/dtolnay/cxx/issues/728
