### ISSUE TITLE
Separating CFLAGS or CXXFLAGS by space causes problem in space separated paths

### ISSUE THREAD

**Issue by petercommand** [alexcrichton/cc-rs#80]
Environment: windows 7 x86_64, rust 1.8 msvc
When I am trying to build llvm-sys with msvc, this problem happens as LLVM is installed in the "Program Files" folder. This path is then separated into two different tokens and passed as two different parameters to the compiler, causing unintended effects
https://github.com/alexcrichton/gcc-rs/blob/master/src/lib.rs#L681

**Comment by alexcrichton** [comment]
Yeah this is an unfortunate side-effect of not having a well-defined "list of strings" format for environment variables. This crate doesn't fork out to bash, so shell escaping doesn't work as one would "naturally expect" sometimes. 

We can perhaps invent our own escaping syntax, but for now this is just an unfortunate "feature" until we can invent something like that.

**Comment by alexcrichton** [comment]
I'm going to close this for now since I don't think there's a viable solution for this, this is sort of just how the crate work at this point.
